const Slovar = {
	"ang": {
		naslov: "Angleški nepravilni glagoli",
		opis: "Izpolni prazne okvirčke. Kjer sta možna dva odgovora, zapiši le enega. Pri glagolih z dvema oblikama (na primer 'dreamt/dreamed') zapiši samo tisto obliko, ki se konča s t.",
		glagoli: [
			["arise", "arose", "arisen", "vstati"],
			["awake", "awoke", "awoken", "zbuditi se"],
			["be", "was", "been", "biti"],
			["bear", "bore", "born", "nositi"],
			["beat", "beat", "beaten", "tolči"],
			["become", "became", "become", "postati"],
			["befall", "befell", "befallen", "dogoditi se"],
			["begin", "began", "begun", "začeti"],
			["bend", "bent", "bent", "upogniti"],
			["beseech", "besought", "besought", "rotiti"],
			["bet", "bet", "bet", "staviti"],
			["bid", "bid", "bid", "ponuditi"],
			["bind", "bound", "bound", "vezati"],
			["bite", "bit", "bitten", "gristi"],
			["bleed", "bled", "bled", "krvaveti"],
			["blow", "blew", "blown", "pihati"],
			["break", "broke", "broken", "zlomiti"],
			["breed", "bred", "bred", "vzgojiti"],
			["bring", "brought", "brought", "prinesti"],
			["broadcast", "broadcast", "broadcast", "oddajati"],
			["build", "built", "built", "graditi"],
			["burn", "burnt", "burnt", "goreti"],
			["burst", "burst", "burst", "počiti"],
			["buy", "bought", "bought", "kupiti"],
			["cast", "cast", "cast", "vreči"],
			["catch", "caught", "caught", "ujeti"],
			["choose", "chose", "chosen", "izbrati"],
			["cling", "clung", "clung", "okleniti se"],
			["come", "came", "come", "priti"],
			["cost", "cost", "cost", "stati"],
			["creep", "crept", "crept", "plaziti se"],
			["cut", "cut", "cut", "rezati"],
			["deal", "dealt", "dealt", "deliti"],
			["dig", "dug", "dug", "kopati"],
			["do", "did", "done", "delati"],
			["draw", "drew", "drawn", "vleči"],
			["dream", "dreamt", "dreamt", "sanjati"],
			["drink", "drank", "drunk", "piti"],
			["drive", "drove", "driven", "gnati"],
			["dwell", "dwelt", "dwelt", "stanovati"],
			["eat", "ate", "eaten", "jesti"],
			["fall", "fell", "fallen", "pasti"],
			["feed", "fed", "fed", "hraniti"],
			["feel", "felt", "felt", "čutiti"],
			["fight", "fought", "fought", "boriti se"],
			["find", "found", "found", "najti"],
			["flee", "fled", "fled", "bežati"],
			["fly", "flew", "flown", "leteti"],
			["fling", "flung", "flung", "vreči"],
			["forbid", "forbade", "forbidden", "prepovedati"],
			["foresee", "foresaw", "foreseen", "predvidevati"],
			["forget", "forgot", "forgotten", "pozabiti"],
			["forgive", "forgave", "forgiven", "odpustiti"],
			["forsake", "forsook", "forsaken", "zapustiti"],
			["freeze", "froze", "frozen", "zmrzniti"],
			["get", "got", "got", "dobiti"],
			["give", "gave", "given", "dati"],
			["go", "went", "gone", "iti"],
			["grind", "ground", "ground", "zmleti"],
			["grow", "grew", "grown", "rasti"],
			["hang", "hung", "hung", "viseti"],
			["have", "had", "had", "imeti"],
			["hear", "heard", "heard", "slišati"],
			["hide", "hid", "hidden", "skriti"],
			["hit", "hit", "hit", "zadeti"],
			["hold", "held", "held", "držati"],
			["hurt", "hurt", "hurt", "raniti"],
			["keep", "kept", "kept", "držati (se)"],
			["kneel", "knelt", "knelt", "klečati"],
			["knit", "knit", "knit", "plesti"],
			["know", "knew", "known", "vedeti"],
			["lay", "laid", "laid", "položiti"],
			["lead", "led", "led", "voditi"],
			["lean", "leant", "leant", "sloneti"],
			["leap", "leapt", "leapt", "skočiti"],
			["learn", "learnt", "learnt", "učiti se"],
			["leave", "left", "left", "zapustiti"],
			["lend", "lent", "lent", "posoditi"],
			["let", "let", "let", "pustiti"],
			["lie", "lay", "lain", "ležati"],
			["light", "lit", "lit", "prižgati"],
			["lose", "lost", "lost", "izgubiti"],
			["make", "made", "made", "narediti"],
			["mean", "meant", "meant", "pomeniti"],
			["meet", "met", "met", "srečati"],
			["mislay", "mislaid", "mislaid", "založiti"],
			["mistake", "mistook", "mistaken", "napak razumeti"],
			["mow", "mowed", "mown", "kositi"],
			["pay", "paid", "paid", "plačati"],
			["put", "put", "put", "položiti"],
			["quit", "quit", "quit", "zapustiti"],
			["read", "read", "read", "čitati"],
			["rid", "rid", "rid", "osvoboditi (se)"],
			["ride", "rode", "ridden", "jahati"],
			["ring", "rang", "rung", "zvoniti"],
			["rise", "rose", "risen", "vstati"],
			["run", "ran", "run", "teči"],
			["saw", "sawed", "sawn", "žagati"],
			["say", "said", "said", "reči"],
			["see", "saw", "seen", "videti"],
			["seek", "sought", "sought", "iskati"],
			["sell", "sold", "sold", "prodati"],
			["send", "sent", "sent", "poslati"],
			["set", "set", "set", "postaviti"],
			["sew", "sewed", "sewn", "šivati"],
			["shake", "shook", "shaken", "tresti"],
			["shed", "shed", "shed", "razliti"],
			["shine", "shone", "shone", "sijati"],
			["shoot", "shot", "shot", "streljati"],
			["show", "showed", "shown", "pokazati"],
			["shred", "shred", "shred", "razrezati"],
			["shrink", "shrank", "shrunk", "skrčiti se"],
			["shut", "shut", "shut", "zapreti"],
			["sing", "sang", "sung", "peti"],
			["sink", "sank", "sunk", "potopiti se"],
			["sit", "sat", "sat", "sedeti"],
			["slay", "slew", "slain", "ubiti"],
			["sleep", "slept", "slept", "spati"],
			["slide", "slid", "slid", "drseti"],
			["sling", "slung", "slung", "vreči"],
			["slink", "slunk", "slunk", "laziti"],
			["slit", "slit", "slit", "razparati"],
			["smell", "smelt", "smelt", "vohati"],
			["sow", "sowed", "sown", "sejati"],
			["speak", "spoke", "spoken", "govoriti"],
			["speed", "sped", "sped", "hiteti"],
			["spell", "spelt", "spelt", "črkovati"],
			["spend", "spent", "spent", "izdati"],
			["spill", "spilt", "spilt", "razliti"],
			["spin", "spun", "spun", "presti"],
			["spit", "spat", "spat", "pljuvati"],
			["split", "split", "split", "cepiti"],
			["spoil", "spoilt", "spoilt", "pokvariti"],
			["spread", "spread", "spread", "razprostreti"],
			["spring", "sprang", "sprung", "skakati"],
			["stand", "stood", "stood", "stati"],
			["steal", "stole", "stolen", "krasti"],
			["stick", "stuck", "stuck", "zatakniti"],
			["sting", "stung", "stung", "pičiti"],
			["stink", "stank", "stunk", "smrdeti"],
			["stride", "strode", "stridden", "stopati"],
			["strike", "struck", "struck", "udariti"],
			["string", "strung", "strung", "napeti"],
			["strive", "strove", "striven", "stremeti"],
			["swear", "swore", "sworn", "priseči"],
			["sweat", "sweat", "sweat", "potiti se"],
			["sweep", "swept", "swept", "pomesti"],
			["swell", "swelled", "swollen", "oteči"],
			["swim", "swam", "swum", "plavati"],
			["swing", "swung", "swung", "nihati"],
			["take", "took", "taken", "vzeti"],
			["teach", "taught", "taught", "učiti"],
			["tear", "tore", "torn", "raztrgati"],
			["tell", "told", "told", "povedati"],
			["think", "thought", "thought", "misliti"],
			["throw", "threw", "thrown", "vreči"],
			["understand", "understood", "understood", "razumeti"],
			["wake", "woke", "woken", "prebuditi [se]"],
			["wear", "wore", "worn", "nositi"],
			["weave", "wove", "woven", "tkati"],
			["weep", "wept", "wept", "jokati"],
			["wet", "wet", "wet", "močiti"],
			["win", "won", "won", "zmagati"],
			["wind", "wound", "wound", "viti se"],
			["withdraw", "withdrew", "withdrawn", "umakniti se"],
			["withhold", "withheld", "withheld", "zadržati"],
			["withstand", "withstood", "withstood", "upirati se"],
			["write", "wrote", "written", "pisati"],
		],
	}, 
	"nem": {
		naslov: "Nemški nepravilni glagoli",
		opis: "Izpolni prazne okvirčke. Kjer sta možna dva odgovora, zapiši le enega. Posebne znake lahko pišeš v 'slovenski' obliki: ß = ss, ä = ae...",
		glagoli: [
			["backen", "backte", "hat gebacken", "peči"],
			["beginnen", "begann", "hat begonnen", "začeti"],
			["bieten", "bietet", "hat geboten", "ponuditi"],
			["bitten", "bat,hat", "gebeten", "prositi"],
			["bleiben", "blieb", "ist geblieben", "ostati"],
			["brechen", "bricht", "ist gebrochen", "razbiti"],
			["bringen", "brachte", "hat gebracht", "prinesti"],
			["denken", "dachte", "hat gedacht", "misliti"],
			["essen", "aß", "hat gegessen", "jesti"],
			["fahren", "fuhr", "ist gefahren", "voziti se"],
			["fallen", "fiel", "ist gefallen", "pasti"],
			["finden", "fand", "hat gefunden", "najti"],
			["fliegen", "flog", "ist geflogen", "leteti"],
			["geben", "gab", "hat gegeben", "dati"],
			["gefallen", "gefiel", "hat gefallen", "ugajati/biti všeč"],
			["gehen", "ging", "ist gegangen", "iti"],
			["genießen", "genoss", "hat genossen", "uživati"],
			["haben", "hatte", "hat gehabt", "imeti"],
			["hängen", "hing", "hat gehangen", "viseti"],
			["helfen", "half", "hat geholfen", "pomagati"],
			["kommen", "kam", "ist gekommen", "priti"],
			["laufen", "lief", "ist gelaufen", "teči"],
			["lesen", "las", "hat gelesen", "brati"],
			["liegen", "lag", "hat gelegen", "ležati"],
			["nehmen", "nahm", "hat genommen", "vzeti"],
			["reiten", "ritt", "ist geritten", "jahati"],
			["rufen", "rief", "hat gerufen", "klicati"],
			["schlafen", "schlief", "hat geschlafen", "spati"],
			["schließen", "schloss", "hat geschlossen", "zapirati"],
			["schreiben", "schrieb", "hat geschrieben", "pisati"],
			["schwimmen", "schwamm", "ist geschwommen", "plavati"],
			["sehen", "sah", "hat gesehen", "gledati"],
			["sein", "war", "ist gewesen", "biti"],
			["singen", "sang", "hat gesungen", "peti"],
			["sitzen", "saß", "hat gesessen", "sedeti"],
			["sprechen", "sprach", "hat gesprochen", "govoriti"],
			["stehen", "stand", "hat gestanden", "stati"],
			["sterben", "starb", "ist gestorben", "umreti"],
			["vergessen", "vergaß", "hat vergessen", "pozabiti"],
			["waschen", "wuchs", "ist gewaschen", "prati"],
			["werden", "wurde", "ist geworden", "postajati"],
			["wissen", "wusste", "hat gewusst", "vedeti"],
		],
	}
}